name: Build and Package VerneMQ

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-20.04, debian-11, alpine-3.16]
        arch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker Image
      run: |
        docker buildx build --platform linux/${{ matrix.arch }} \
        --file docker/Dockerfile \
        --output type=docker \
        --tag vernemq:${{ matrix.os }}-${{ matrix.arch }} .

    - name: Create Packages
      run: |
        docker run --rm \
        -v $PWD:/output vernemq:${{ matrix.os }}-${{ matrix.arch }} \
        sh -c 'mv /vernemq*.deb /vernemq*.apk /output/'

    - name: Upload Package Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: vernemq-${{ matrix.os }}-${{ matrix.arch }}
        path: "*.deb, *.apk"
