name: Build VerneMQ .deb Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t vernemq-deb-builder -f docker/Dockerfile.debian .

      - name: Run Docker Container to Create .deb
        run: docker run --rm -v ${{ github.workspace }}/output:/output vernemq-builder

      - name: Upload .deb as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: vernemq-deb-package
          path: ./output/vernemq_2.0.1_amd64.deb
